import Link from 'next/link';
import {db} from '@/lib/db';import {listEvidence} from '@/lib/growth-store';
import {hasOperatorAccess} from '@/lib/operator-access';
import {experimentComparison} from '@/lib/growth-operations';import type {OperationReport,ChangeExperiment,CitationObservation} from '@/lib/growth-operations';
import type {LiveReport,Lane} from '@/lib/live-verification';
import {operateAction,unlockAction,contentAction,citationAction,experimentAction,indexNowAction} from './actions';
import {SubmitButton} from '@/components/ui';
export const dynamic='force-dynamic';export const maxDuration=180;
const number=(n:number|null|undefined)=>typeof n==='number'?n.toLocaleString():'미측정';
const field='w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm';
const section='rounded-xl border border-zinc-200 bg-white p-5';
function Change({current,previous}:{current:number|null|undefined;previous:number|null|undefined}){
 if(typeof current!=='number'||typeof previous!=='number')return <span className="text-zinc-500">전후 비교 자료 없음</span>;
 const delta=current-previous;return <span>{delta>=0?'+':''}{number(delta)} {previous!==0?`(${(delta/previous*100).toFixed(1)}%)`:'(이전 0: 증가율 계산 안 함)'}</span>;
}
function LaneCard({lane,report}:{lane:Lane;report:LiveReport|null}){
 const checks=report?.checks.filter(c=>c.lane===lane)??[],fails=checks.filter(c=>c.status==='fail').length,unknown=checks.filter(c=>c.status==='unknown').length;
 return <article className="rounded-lg border border-zinc-200 bg-white p-4"><h3 className="font-semibold">{lane}</h3><p className="mt-2 text-xl font-bold">{!checks.length?'미검사':fails?`${fails}개 차단`:unknown?`${unknown}개 확인 불가`:`${checks.filter(c=>c.status==='pass').length}/${checks.length} 확인`}</p><p className="mt-1 text-xs text-zinc-500">{lane==='SEO'?'초기 HTML·정본·검색 차단':lane==='AEO'?'첫 답변의 표시 여부':lane==='GEO'?'근거·기준일·검색봇 정책':'네이버 Yeti 접근 정책'}</p></article>;
}
export default async function OperationsPage({params}:{params:Promise<{siteId:string}>}){
 const {siteId}=await params;
 if(!await hasOperatorAccess())return <section className={section}><h2 className="text-xl font-bold">성과 검증 운영자 접속</h2><p className="my-3 text-sm text-zinc-600">측정 데이터와 변경 기능은 운영자만 사용할 수 있습니다. 운영 환경에 SGO_OPERATOR_TOKEN을 설정하세요.</p><form action={unlockAction.bind(null,siteId)} className="max-w-sm space-y-3"><label className="block text-sm">운영자 암호<input name="password" type="password" required className={field}/></label><SubmitButton pendingText="확인 중">접속</SubmitButton></form></section>;
 const [operations,citations,experiments,deliveries,indexnow,pages]=await Promise.all([listEvidence<OperationReport>(siteId,'operation',8),listEvidence<CitationObservation>(siteId,'citation',30),listEvidence<ChangeExperiment>(siteId,'experiment',20),listEvidence<{stage:string;message:string}>(siteId,'delivery',10),listEvidence<{status:string;detail:string}>(siteId,'indexnow',5),db.pages.bySite(siteId)]);
 const latest=operations[0]?.payload??null,verification=latest?.verification??null,search=latest?.search,analytics=latest?.analytics;
 const stale=operations[0]?Date.now()-Date.parse(operations[0].createdAt)>7*86400000:false;
 return <div className="space-y-6" data-testid="growth-operations">
  <header className="rounded-xl bg-zinc-900 px-6 py-7 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-zinc-400">Search Growth OS / Evidence workspace</p><h2 className="mt-2 text-3xl font-bold">성과 검증</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-300">실제로 읽히는 페이지인지 확인하고, 검색 클릭 → 방문 → 문의를 분리해 측정합니다. 기능 실행이나 기술 검사 통과를 방문 증가로 보고하지 않습니다.</p><p className="mt-3 text-xs text-zinc-400">마지막 실행: {operations[0]?.createdAt??'실행 전'} {stale?' · 오래된 기록':''}</p></header>
  <section className={section}><h3 className="font-semibold">실제 URL 검사 + 실측 데이터 수집</h3><form action={operateAction.bind(null,siteId)} className="mt-3 flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm">검사할 URL 또는 경로<input name="target" defaultValue="/" placeholder="/services/ai-website" className={field}/></label><SubmitButton pendingText="URL·검색·방문 자료 확인 중…">검증·측정 실행</SubmitButton></form><p className="mt-2 text-xs text-zinc-500">사이트를 수정하지 않는 읽기 검사입니다. 외부 발행과 URL 제출은 별도 작업입니다.</p></section>
  {latest?.errors.length?<aside className="rounded-lg border border-amber-300 bg-amber-50 p-4"><h3 className="font-semibold">측정 연결 확인 필요</h3>{latest.errors.map((e,i)=><p key={i} className="mt-1 break-words text-sm">{e}</p>)}<p className="mt-2 text-xs">미측정을 0으로 바꾸지 않습니다. GSC·GA4 자격증명은 서버 환경변수로만 설정합니다.</p></aside>:null}
  <section><div className="mb-2 flex flex-wrap justify-between gap-2"><h3 className="font-semibold">변경 전후 성과</h3><p className="text-xs text-zinc-500">{search?`${search.previous.period.startDate}~${search.previous.period.endDate} → ${search.current.period.startDate}~${search.current.period.endDate}`:'동일 길이의 비교 기간 대기'}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
   {label:'검색 노출',current:search?.current.totals?.impressions,previous:search?.previous.totals?.impressions},
   {label:'검색 클릭',current:search?.current.totals?.clicks,previous:search?.previous.totals?.clicks},
   {label:'검색 유입 방문',current:analytics?.sessions.current,previous:analytics?.sessions.previous},
   {label:'설정된 문의 이벤트',current:analytics?.leadEvents.current,previous:analytics?.leadEvents.previous}
  ].map(card=><article key={card.label} className="rounded-lg border border-zinc-200 bg-white p-4"><p className="text-sm text-zinc-500">{card.label}</p><p className="mt-2 text-3xl font-bold">{number(card.current)}</p><p className="mt-2 text-xs"><Change current={card.current} previous={card.previous}/></p></article>)}</div><p className="mt-3 text-xs leading-5 text-zinc-500">문의 이벤트 ≠ 고유 고객 ≠ 유효 상담. 실제 색인율과 유효 상담은 아직 미측정입니다. GSC는 사이트 URL 범위를 필터링한 결과이며 검색어 행 합산과 다릅니다. 전후 변화만으로 개선 원인을 입증하지 않습니다. {analytics?.status==='limited'?'GA4 임계값/샘플링 제한 있음.':''}</p></section>
  <section><h3 className="mb-2 font-semibold">검색 채널별 확인 항목</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(['SEO','AEO','GEO','NEO'] as Lane[]).map(lane=><LaneCard key={lane} lane={lane} report={verification}/>)}</div><p className="mt-2 text-xs text-zinc-500">검사 항목 충족도이지 검색 순위·AI 인용 확률 점수가 아닙니다. LLM 내부 학습 여부는 판정하지 않습니다.</p></section>
  {verification?<section className={section}><h3 className="font-semibold">검사 근거 · {verification.status==='verified'?'기술 확인 완료':'차단/미확인 항목 있음'}</h3><a href={verification.url} className="mt-1 block break-all text-xs text-blue-700">{verification.url}</a><div className="mt-4 divide-y divide-zinc-100">{verification.checks.map(c=><article key={c.code} className="grid gap-2 py-3 sm:grid-cols-[150px_1fr]"><div><b className="text-sm">{c.lane} · {c.status==='pass'?'확인':c.status==='fail'?'차단':c.status==='warn'?'보강':'미확인'}</b><p className="text-xs text-zinc-400">{c.code}</p></div><div><p className="break-words text-sm">{c.detail}</p>{c.status!=='pass'&&<p className="mt-1 text-xs text-zinc-500">조치: {c.remedy}</p>}</div></article>)}</div><form action={indexNowAction.bind(null,siteId)} className="mt-3"><SubmitButton pendingText="키·URL 확인 후 제출 중" variant="secondary">검증한 URL을 IndexNow에 제출</SubmitButton></form><p className="mt-2 text-xs text-zinc-500">명시적으로 누를 때만 제출합니다. 공개 키 확인과 24시간 이내 URL 검증이 필요합니다. 접수는 색인 완료가 아닙니다.</p>{indexnow.map(r=><p key={r.id} className="mt-2 text-xs">{r.createdAt} · {r.payload.detail}</p>)}</section>:null}
  <section className={section}><h3 className="font-semibold">새 글보다 먼저 개선할 기존 페이지</h3>{search?.queryPages.length?<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">실제 검색어 / 페이지</th><th className="p-2">노출</th><th className="p-2">클릭</th><th className="p-2">순위</th></tr></thead><tbody>{search.queryPages.filter(r=>r.impressions>=100&&r.position>=4&&r.position<=20).sort((a,b)=>b.impressions-a.impressions).slice(0,10).map((r,i)=><tr key={i} className="border-t border-zinc-100"><td className="p-2">{r.keys[0]}<a className="block max-w-lg truncate text-xs text-blue-700" href={r.keys[1]}>{r.keys[1]}</a></td><td className="p-2">{number(r.impressions)}</td><td className="p-2">{number(r.clicks)}</td><td className="p-2">{r.position.toFixed(1)}</td></tr>)}</tbody></table></div>:<p className="mt-2 text-sm text-zinc-500">실제 검색어·페이지 자료가 연결되면 후보가 나타납니다. 추정 검색량으로 빈 표를 채우지 않습니다.</p>}<Link href={`/sites/${siteId}/growth`} className="mt-3 inline-block text-sm text-blue-700">근거별 개선 제안 보기 →</Link></section>
  <section className={section}><h3 className="font-semibold">직답·출처·기준일을 실제 콘텐츠에 반영</h3><p className="mt-1 text-xs text-zinc-500">원본 버전을 보관하고 검토 상태로 전환합니다. 외부 사이트에 자동 게시하지 않습니다.</p>{pages.length?<form action={contentAction.bind(null,siteId)} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm sm:col-span-2">대상 페이지<select name="pageId" className={field}>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="text-sm sm:col-span-2">질문에 대한 직답<textarea name="directAnswer" required className={field} rows={3}/></label><label className="text-sm">실제 자료 기준일<input type="date" name="dataAsOf" required className={field}/></label><label className="text-sm">검토자<input name="reviewer" required className={field}/></label><label className="text-sm sm:col-span-2">확인한 출처 URL (한 줄에 하나)<textarea name="sources" className={field} rows={3}/></label><SubmitButton pendingText="버전 보관·품질 재검사 중">콘텐츠에 반영하고 재검사</SubmitButton></form>:<p className="mt-3 text-sm text-zinc-500">이 엔진에 등록된 페이지가 아직 없습니다. 기존 외부 페이지 검사는 위에서 바로 실행할 수 있습니다.</p>}</section>
  <section className={section}><h3 className="font-semibold">변경 이력과 전후 관찰</h3><form action={experimentAction.bind(null,siteId)} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="name" placeholder="실제로 적용한 변경명" aria-label="변경명" required className={field}/><input name="target" placeholder="변경한 페이지 경로" aria-label="변경 경로" required className={field}/><input name="changeProof" type="url" placeholder="변경 커밋/배포 증거 URL" aria-label="변경 증거" required className={field}/><input name="hypothesis" placeholder="어떤 문제를 어떻게 개선했는지" aria-label="변경 가설" required className={field}/><SubmitButton pendingText="기준선 보관 중" variant="secondary">적용한 변경과 기준선 기록</SubmitButton></form>{experiments.map(row=><article key={row.id} className="mt-4 rounded-md bg-zinc-50 p-3 text-sm"><b>{row.payload.name}</b><p>{row.payload.hypothesis}</p><p className="mt-1 text-xs">{experimentComparison(row.payload,latest).status}</p><a href={row.payload.changeProof} className="text-xs text-blue-700">변경 증거</a></article>)}</section>
  <section className={section}><h3 className="font-semibold">AI 인용 관측 기록</h3><p className="mt-1 text-xs text-zinc-500">실제 검색 답변의 증거를 보관하는 수동 관측 기능입니다. API가 검색했다고 꾸미거나 모델의 브랜드 지식을 추정하지 않습니다.</p><form action={citationAction.bind(null,siteId)} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="question" placeholder="실제로 질문한 문장" aria-label="관측 질문" required className={field}/><input name="engine" placeholder="엔진·모델·검색 모드" aria-label="관측 엔진" required className={field}/><select name="result" aria-label="관측 결과" className={field}><option value="cited">우리 URL 인용</option><option value="mentioned">이름만 언급</option><option value="not_seen">이 답변에서 미관측</option></select><input type="datetime-local" name="observedAt" aria-label="관측 시각" required className={field}/><input name="citedUrl" placeholder="인용된 우리 URL" aria-label="인용 URL" className={field}/><input type="url" name="evidenceUrl" placeholder="답변 공유/화면 증거 HTTPS URL" aria-label="관측 증거" required className={field}/><textarea name="excerpt" placeholder="실제 답변 발췌 20자 이상" aria-label="답변 발췌" required minLength={20} rows={3} className={`${field} sm:col-span-2`}/><SubmitButton pendingText="관측 보관 중" variant="secondary">증거와 함께 기록</SubmitButton></form>{citations.map(row=><article key={row.id} className="mt-3 border-t pt-3 text-sm"><b>{row.payload.engine} · {row.payload.result}</b><p>{row.payload.question}</p><a href={row.payload.evidenceUrl} className="text-xs text-blue-700">{row.payload.observedAt} · 증거 확인</a></article>)}</section>
  {deliveries.length?<section className={section}><h3 className="font-semibold">실제 발행 상태</h3>{deliveries.map(row=><p key={row.id} className="mt-2 text-sm">{row.createdAt} · {row.payload.stage} · {row.payload.message}</p>)}</section>:null}
  <section className={section}><h3 className="font-semibold">실행 기록</h3>{operations.length?operations.map(row=><p key={row.id} className="mt-2 break-all text-xs text-zinc-600">{row.createdAt} · {row.target} · {row.payload.verification.status} · GSC {row.payload.search?'관측 기록 있음':'미연결/실패'}</p>):<p className="mt-2 text-sm text-zinc-500">아직 실행 기록이 없습니다.</p>}</section>
 </div>;
}
